### ISSUE TITLE
RSS/Atom feed

### ISSUE THREAD

**Issue by migueldvb** [kgullikson88/blog#1]
Could you generate an Atom or RSS feed of the blog in `pelicanconf.py`?

**Comment by kgullikson88** [comment]
I'm not actually sure how to do that, but will definitely look into it!

**Comment by kgullikson88** [comment]
Alright, I think I got links to the feeds in my [About page](http://kgullikson88.github.io/blog/pages/about.html). Let me know if it works!

**Comment by migueldvb** [comment]
Thank you! It works well for me.
